// Auto-generated by export_js.php — 2026-07-03 10:50:13
// ⚠️ 請勿手動編輯此檔案，請透過後台管理系統更新

const BEYBLADE_DATABASE = {
    parts: {
        blades: {
            "Clock_Mirage_v1": {
                name: "時鐘幻象", type: "耐力型", weight: 37.7,
                shopeeUrl: "https://s.shopee.tw/1gGU9BejAU",
                stats: { atk: 10, def: 10, sta: 80},
                versions: ["UX-16-01", "UX-16-02", "UX-16-03"]
            },
            "Cobalt_Drake_v1": {
                name: "蒼穹龍神", type: "攻擊型", weight: 37.3,
                shopeeUrl: "https://s.shopee.tw/7VE99gmDpo",
                stats: { atk: 65, def: 30, sta: 20},
                versions: ["BXG-23"]
            },
            "Cobalt_Drake_v2": {
                name: "蒼穹龍神 (強化)", type: "攻擊型", weight: 37.3,
                shopeeUrl: "https://s.shopee.tw/3Vi0ONWoaN",
                stats: { atk: 70, def: 35, sta: 25},
                versions: ["BX-46-01", "BXH-01"]
            },
            "Dran_Dagger_v1": {
                name: "蒼龍利刃", type: "攻擊型", weight: 36,
                shopeeUrl: "https://s.shopee.tw/110cAEl1Mo",
                stats: { atk: 50, def: 25, sta: 25},
                versions: ["BX-20-01", "BX-31-04", "UX-18-05"]
            },
            "Dran_Dagger_v2": {
                name: "蒼龍利刃 (強化)", type: "攻擊型", weight: 36,
                shopeeUrl: "https://s.shopee.tw/4qDKjMUPMj",
                stats: { atk: 55, def: 30, sta: 30},
                versions: ["BXG-14", "BXG-25-03"]
            },
            "Dran_Sword_v1": {
                name: "蒼龍神劍", type: "攻擊型", weight: 35.1,
                shopeeUrl: "https://s.shopee.tw/2qSDoE4DbQ",
                stats: { atk: 55, def: 25, sta: 20},
                versions: ["BX-01", "BX-07", "BX-14-03", "BX-17-01", "BX-22"]
            },
            "Dran_Sword_v2": {
                name: "蒼龍神劍 (強化)", type: "攻擊型", weight: 35.1,
                shopeeUrl: "https://s.shopee.tw/4ftrzkfnIf",
                stats: { atk: 60, def: 30, sta: 25},
                versions: ["BXC-00-01", "BXC-00-02", "BXC-00-03", "BXC-04", "BXG-12-04", "BXG-18", "BXG-25-01", "BXG-52"]
            },
            "DRANZER_SPIRAL_v1": {
                name: "烈焰飛鳳S", type: "平衡型", weight: 27.7,
                shopeeUrl: "https://s.shopee.tw/7KuhDQgryq",
                stats: { atk: 35, def: 30, sta: 35},
                versions: ["BXG-01", "BXG-15"]
            },
            "Hells_Chain_v1": {
                name: "惡魔鎖鏈", type: "平衡型", weight: 33.2,
                shopeeUrl: "https://s.shopee.tw/4ftuTbkbub",
                stats: { atk: 35, def: 40, sta: 25},
                versions: ["BX-21-01", "BX-31-03"]
            },
            "Hells_Scythe_v1": {
                name: "惡魔紅鐮", type: "平衡型", weight: 33.7,
                shopeeUrl: "https://s.shopee.tw/7VE3MymXxV",
                stats: { atk: 30, def: 35, sta: 35},
                versions: ["BX-02", "BX-08-01", "BX-14-04"]
            },
            "Hells_Scythe_v2": {
                name: "惡魔紅鐮 (強化)", type: "平衡型", weight: 33.7,
                shopeeUrl: "https://s.shopee.tw/9zvOLdWfbN",
                stats: { atk: 35, def: 40, sta: 40},
                versions: ["BX-48-04", "BXG-03"]
            },
            "Knight_Lance_v1": {
                name: "騎士長槍", type: "防禦型", weight: 32.9,
                shopeeUrl: "https://s.shopee.tw/9KfotaZHUt",
                stats: { atk: 25, def: 60, sta: 15},
                versions: ["BX-13", "BX-21-02", "BX-24-03"]
            },
            "Knight_Mail_v1": {
                name: "騎士圓甲", type: "防禦型", weight: 36.7,
                shopeeUrl: "https://s.shopee.tw/W4LTl005x",
                stats: { atk: 10, def: 65, sta: 35},
                versions: ["UX-10-01"]
            },
            "Knight_Mail_v2": {
                name: "騎士圓甲 (強化)", type: "防禦型", weight: 36.7,
                shopeeUrl: "https://s.shopee.tw/9Kfk00o2Iq",
                stats: { atk: 15, def: 70, sta: 40},
                versions: ["BXG-42"]
            },
            "Knight_Shield_v1": {
                name: "騎士重盾", type: "防禦型", weight: 34.8,
                shopeeUrl: "https://s.shopee.tw/6L25yx112O",
                stats: { atk: 20, def: 55, sta: 25},
                versions: ["BX-04", "BX-06", "BX-08-02", "BX-14-05", "BX-20-03"]
            },
            "Knight_Shield_v2": {
                name: "騎士重盾 (強化)", type: "防禦型", weight: 34.8,
                shopeeUrl: "https://s.shopee.tw/5L9YnA9Jj9",
                stats: { atk: 25, def: 60, sta: 30},
                versions: ["BXH-02"]
            },
            "Leon_Claw_v1": {
                name: "雄獅獵爪", type: "平衡型", weight: 31.4,
                shopeeUrl: "https://s.shopee.tw/1BKAMqJfOf",
                stats: { atk: 40, def: 40, sta: 20},
                versions: ["BX-15", "BX-24-05", "UX-12-04"]
            },
            "Leon_Claw_v2": {
                name: "雄獅獵爪 (強化)", type: "平衡型", weight: 31.4,
                shopeeUrl: "https://s.shopee.tw/9pc8guFCbP",
                stats: { atk: 45, def: 45, sta: 25},
                versions: ["BXG-05"]
            },
            "Phoenix_Feather_v1": {
                name: "鳳凰翔羽", type: "攻擊型", weight: 33.3,
                shopeeUrl: "https://s.shopee.tw/1LdlmHsAkP",
                stats: { atk: 50, def: 20, sta: 30},
                versions: ["BXC-01", "UX-12-05"]
            },
            "Phoenix_Feather_v2": {
                name: "鳳凰翔羽 (強化)", type: "攻擊型", weight: 33.3,
                shopeeUrl: "https://s.shopee.tw/1VxByfTJUH",
                stats: { atk: 55, def: 25, sta: 35},
                versions: ["BXC-08"]
            },
            "Phoenix_Wing_v1": {
                name: "鳳凰飛翼", type: "攻擊型", weight: 39,
                shopeeUrl: "https://s.shopee.tw/30lfhEgltA",
                stats: { atk: 60, def: 25, sta: 15},
                versions: ["BX-35-05"]
            },
            "Phoenix_Wing_v2": {
                name: "鳳凰飛翼 (強化)", type: "攻擊型", weight: 39,
                shopeeUrl: "https://s.shopee.tw/BRUK3vlgu",
                stats: { atk: 65, def: 30, sta: 20},
                versions: ["BX-23", "BXC-05", "BXG-35"]
            },
            "Rhino_Horn_v1": {
                name: "戰犀重角", type: "防禦型", weight: 32.7,
                shopeeUrl: "https://s.shopee.tw/5VTEaxNDUI",
                stats: { atk: 20, def: 50, sta: 30},
                versions: ["BX-19", "BX-31-06"]
            },
            "Shark_Edge_v1": {
                name: "鮫鯊鋒鰭", type: "攻擊型", weight: 34.5,
                shopeeUrl: "https://s.shopee.tw/7fXmCKupNa",
                stats: { atk: 60, def: 25, sta: 15},
                versions: ["BX-14-01", "BX-14-02", "BX-20-02", "BX-31-05"]
            },
            "Shark_Edge_v2": {
                name: "鮫鯊鋒鰭 (強化)", type: "攻擊型", weight: 34.5,
                shopeeUrl: "https://s.shopee.tw/3LOn2VrG69",
                stats: { atk: 65, def: 30, sta: 20},
                versions: ["BX-48-02", "BXG-06", "BXG-55"]
            },
            "Shark_Scale_v1": {
                name: "鮫鯊狂鱗", type: "攻擊型", weight: 37.6,
                shopeeUrl: "https://s.shopee.tw/5VT0ekUta4",
                stats: { atk: 70, def: 15, sta: 15},
                versions: ["UX-15-01"]
            },
            "Sphinx_Cowl_v1": {
                name: "魔獸護甲", type: "防禦型", weight: 32.7,
                shopeeUrl: "https://s.shopee.tw/2VpoHsjXVa",
                stats: { atk: 35, def: 55, sta: 10},
                versions: ["BX-27-01", "BX-27-02", "BX-27-03", "UX-07-03"]
            },
            "Unicorn_Sting_v1": {
                name: "幻獸刺心", type: "平衡型", weight: 34,
                shopeeUrl: "https://s.shopee.tw/1Vx74SjJhs",
                stats: { atk: 35, def: 35, sta: 30},
                versions: ["BX-26", "BX-35-03"]
            },
            "Viper_Tail_v1": {
                name: "王蛇鞭尾", type: "耐力型", weight: 34.7,
                shopeeUrl: "https://s.shopee.tw/3B5TmBwnWO",
                stats: { atk: 30, def: 20, sta: 50},
                versions: ["BX-16-01", "BX-16-02", "BX-16-03", "BX-24-04", "BX-35-06"]
            },
            "Wizard_Arrow_v1": {
                name: "魔導幻箭", type: "耐力型", weight: 31.8,
                shopeeUrl: "https://s.shopee.tw/7AbCyST2LA",
                stats: { atk: 15, def: 30, sta: 55},
                versions: ["BX-03", "BX-05", "BX-08-03", "BX-14-06", "BX-17-02", "BX-21-03", "BX-24-06"]
            },
            "Wizard_Rod_v1": {
                name: "魔導神杖", type: "耐力型", weight: 35.3,
                shopeeUrl: "https://s.shopee.tw/1LdRZ11aha",
                stats: { atk: 15, def: 25, sta: 60},
                versions: ["BX-35-04", "UX-03", "UX-04-02"]
            },
            "Wizard_Rod_v2": {
                name: "魔導神杖 (強化)", type: "耐力型", weight: 35.3,
                shopeeUrl: "https://s.shopee.tw/LkuNCqZ9P",
                stats: { atk: 20, def: 30, sta: 65},
                versions: ["BXH-09"]
            },
            "Wyvern_Gale_v1": {
                name: "飛龍旋翼", type: "耐力型", weight: 31.9,
                shopeeUrl: "https://s.shopee.tw/3qKxhvS3iz",
                stats: { atk: 10, def: 40, sta: 50},
                versions: ["BX-24-01", "BX-24-02", "UX-07-02", "UX-12-06"]
            },
        },
        ratchets: {
            "0-60": { name: "0-60", height: 60, weight: 6.8, shopeeUrl: "https://s.shopee.tw/50Wt6R47QG", stats: { atk: 3, def: 14, sta: 13} },
            "0-70": { name: "0-70", height: 70, weight: 7, shopeeUrl: "https://s.shopee.tw/W4TkHNEb5", stats: { atk: 3, def: 13, sta: 14} },
            "0-80": { name: "0-80", height: 80, weight: 7.6, shopeeUrl: "https://s.shopee.tw/1Vx0lDOJro", stats: { atk: 3, def: 12, sta: 15} },
            "1-50": { name: "1-50", height: 50, weight: 5.7, shopeeUrl: "https://s.shopee.tw/AUrpel0Xx7", stats: { atk: 18, def: 9, sta: 3} },
            "1-60": { name: "1-60", height: 60, weight: 6, shopeeUrl: "https://s.shopee.tw/2LVxCJQYp3", stats: { atk: 17, def: 9, sta: 4} },
            "1-70": { name: "1-70", height: 70, weight: 6.1, shopeeUrl: "https://s.shopee.tw/Ll3YA6AMS", stats: { atk: 17, def: 6, sta: 7} },
            "1-80": { name: "1-80", height: 80, weight: 6.7, shopeeUrl: "https://s.shopee.tw/2BCX00RCA2", stats: { atk: 17, def: 4, sta: 9} },
            "2-60": { name: "2-60", height: 60, weight: 6.2, shopeeUrl: "https://s.shopee.tw/20t6nhRpV1", stats: { atk: 10, def: 13, sta: 7} },
            "2-70": { name: "2-70", height: 70, weight: 6.3, shopeeUrl: "https://s.shopee.tw/9UzIT7TTmD", stats: { atk: 10, def: 12, sta: 8} },
            "2-80": { name: "2-80", height: 80, weight: 6.9, shopeeUrl: "https://s.shopee.tw/qh9RGXeji", stats: { atk: 10, def: 11, sta: 9} },
            "3-60": { name: "3-60", height: 60, weight: 6.4, shopeeUrl: "https://s.shopee.tw/LksodYAsj", stats: { atk: 15, def: 9, sta: 6} },
            "3-70": { name: "3-70", height: 70, weight: 6.4, shopeeUrl: "https://s.shopee.tw/6pyMYdiina", stats: { atk: 15, def: 8, sta: 7} },
            "3-80": { name: "3-80", height: 80, weight: 7.1, shopeeUrl: "https://s.shopee.tw/gNjCwfxIc", stats: { atk: 15, def: 7, sta: 8} },
            "3-85": { name: "3-85", height: 85, weight: 4.7, shopeeUrl: "https://s.shopee.tw/qh9PFfJxf", stats: { atk: 5, def: 15, sta: 10} },
            "4-50": { name: "4-50", height: 50, weight: 5.9, shopeeUrl: "https://s.shopee.tw/9AMJ0boqBA", stats: { atk: 12, def: 13, sta: 5} },
            "4-55": { name: "4-55", height: 55, weight: 4.8, shopeeUrl: "https://s.shopee.tw/9AMS4bk87A", stats: { atk: 7, def: 11, sta: 12} },
            "4-60": { name: "4-60", height: 60, weight: 6.3, shopeeUrl: "https://s.shopee.tw/1gGGOmc9Gq", stats: { atk: 11, def: 13, sta: 6} },
            "4-70": { name: "4-70", height: 70, weight: 6.4, shopeeUrl: "https://s.shopee.tw/1qZgb5bVvt", stats: { atk: 11, def: 12, sta: 7} },
            "4-80": { name: "4-80", height: 80, weight: 7, shopeeUrl: "https://s.shopee.tw/1LdQ0AdPwo", stats: { atk: 11, def: 11, sta: 8} },
            "5-60": { name: "5-60", height: 60, weight: 6.6, shopeeUrl: "https://s.shopee.tw/2VpNOkzfoT", stats: { atk: 12, def: 9, sta: 9} },
            "5-70": { name: "5-70", height: 70, weight: 6.7, shopeeUrl: "https://s.shopee.tw/20t6nq1ZpO", stats: { atk: 12, def: 8.5, sta: 9.5} },
            "5-80": { name: "5-80", height: 80, weight: 7.3, shopeeUrl: "https://s.shopee.tw/2BCX090wUR", stats: { atk: 12, def: 8, sta: 10} },
            "6-60": { name: "6-60", height: 60, weight: 6.1, shopeeUrl: "https://s.shopee.tw/7AbNh2XJiM", stats: { atk: 14, def: 8, sta: 8} },
            "6-70": { name: "6-70", height: 70, weight: 6.3, shopeeUrl: "https://s.shopee.tw/1LdakNnRKc", stats: { atk: 14, def: 7, sta: 9} },
            "6-80": { name: "6-80", height: 80, weight: 6.9, shopeeUrl: "https://s.shopee.tw/2BChjyg2Uo", stats: { atk: 14, def: 6, sta: 10} },
            "7-55": { name: "7-55", height: 55, weight: 5.2, shopeeUrl: "https://s.shopee.tw/6pyP6X4WCn", stats: { atk: 6, def: 14, sta: 10} },
            "7-60": { name: "7-60", height: 60, weight: 7.1, shopeeUrl: "https://s.shopee.tw/7VEE5rsuir", stats: { atk: 8, def: 14, sta: 8} },
            "7-70": { name: "7-70", height: 70, weight: 7.3, shopeeUrl: "https://s.shopee.tw/Lksom7vD6", stats: { atk: 8, def: 12, sta: 10} },
            "7-80": { name: "7-80", height: 80, weight: 7.8, shopeeUrl: "https://s.shopee.tw/6ff76vBzxA", stats: { atk: 7, def: 14, sta: 9} },
            "8-70": { name: "8-70", height: 70, weight: 7.7, shopeeUrl: "https://s.shopee.tw/qhK9hA19E", stats: { atk: 8, def: 10, sta: 12} },
            "9-60": { name: "9-60", height: 60, weight: 6.2, shopeeUrl: "https://s.shopee.tw/W4J157Hs9", stats: { atk: 13, def: 10, sta: 7} },
            "9-65": { name: "9-65", height: 65, weight: 4.5, shopeeUrl: "https://s.shopee.tw/60PQJGTqKH", stats: { atk: 13, def: 10, sta: 7} },
            "9-70": { name: "9-70", height: 70, weight: 6.3, shopeeUrl: "https://s.shopee.tw/5AqJJqSoRg", stats: { atk: 13, def: 10, sta: 7} },
            "9-80": { name: "9-80", height: 80, weight: 6.9, shopeeUrl: "https://s.shopee.tw/9pby8Hx51W", stats: { atk: 13, def: 10, sta: 7} },
            "M-85": { name: "M-85", height: 85, weight: 10.6, shopeeUrl: "https://s.shopee.tw/6AiqVrgQIe", stats: { atk: 8, def: 19, sta: 13} },
        },
        bits: {
            "Accel": { name: "A 加速", type: "攻擊型", weight: 2.6, shopeeUrl: "https://s.shopee.tw/40e9bdi6DI", stats: { atk: 40, def: 10, sta: 10, accel: 40, endurance: 80 } },
            "Ball": { name: "B 球狀軸心", type: "耐力型", weight: 2.1, shopeeUrl: "https://s.shopee.tw/4AxZnwhSsL", stats: { atk: 15, def: 25, sta: 50, accel: 10, endurance: 30 } },
            "Bound Spike": { name: "BS 彈簧防禦軸", type: "防禦型", weight: 2, shopeeUrl: "https://s.shopee.tw/1VwsfCjXva", stats: { atk: 5, def: 60, sta: 30, accel: 5, endurance: 30 } },
            "Cyclone": { name: "C 暴風", type: "攻擊型", weight: 2.1, shopeeUrl: "https://s.shopee.tw/4LH00FgpXO", stats: { atk: 40, def: 5, sta: 10, accel: 45, endurance: 80 } },
            "Disc Ball": { name: "DB 圓盤球狀軸", type: "耐力型", weight: 3.2, shopeeUrl: "https://s.shopee.tw/1LdORAQukH", stats: { atk: 15, def: 20, sta: 55, accel: 10, endurance: 30 } },
            "Disk Spike": { name: "DS 尖錐圓盤軸", type: "防禦型", weight: 3.1, shopeeUrl: "https://s.shopee.tw/3B5L9CpWrD", stats: { atk: 5, def: 55, sta: 40, accel: 10, endurance: 20 } },
            "Dot": { name: "D 圓點", type: "防禦型", weight: 2, shopeeUrl: "https://s.shopee.tw/4VaQCYgCCR", stats: { atk: 10, def: 55, sta: 25, accel: 10, endurance: 30 } },
            "Elevate": { name: "E 仰昇", type: "平衡型", weight: 3.2, shopeeUrl: "https://s.shopee.tw/4ftqOrfYrU", stats: { atk: 30, def: 15, sta: 20, accel: 35, endurance: 30 } },
            "Flat": { name: "F 平底軸心", type: "攻擊型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/9KffxXcyFp", stats: { atk: 40, def: 15, sta: 10, accel: 35, endurance: 80 } },
            "Free Ball": { name: "FB 自由旋轉球狀軸", type: "耐力型", weight: 1.9, shopeeUrl: "https://s.shopee.tw/5q5nnUgOVe", stats: { atk: 10, def: 25, sta: 60, accel: 5, endurance: 30 } },
            "Free Flat": { name: "FF 自由旋轉平軸", type: "攻擊型", weight: 2.1, shopeeUrl: "https://s.shopee.tw/6L2MvGK4sT", stats: { atk: 40, def: 15, sta: 15, accel: 30, endurance: 80 } },
            "Gear Ball": { name: "GB 齒輪球狀軸", type: "耐力型", weight: 2, shopeeUrl: "https://s.shopee.tw/5Aq705jBML", stats: { atk: 10, def: 15, sta: 45, accel: 30, endurance: 30 } },
            "Gear Flat": { name: "GF 齒輪平頭軸", type: "攻擊型", weight: 2.3, shopeeUrl: "https://s.shopee.tw/50WgnmjohI", stats: { atk: 50, def: 5, sta: 5, accel: 40, endurance: 80 } },
            "Gear Needle": { name: "GN 齒輪針狀軸", type: "防禦型", weight: 2, shopeeUrl: "https://s.shopee.tw/4qDj5JHo60", stats: { atk: 20, def: 40, sta: 10, accel: 30, endurance: 30 } },
            "Gear Point": { name: "GP 齒輪尖點軸", type: "平衡型", weight: 2.3, shopeeUrl: "https://s.shopee.tw/6pyKzpPRii", stats: { atk: 30, def: 25, sta: 15, accel: 30, endurance: 80 } },
            "Gear Unite": { name: "GU 齒輪聯合", type: "平衡型", weight: 2.3, shopeeUrl: "https://s.shopee.tw/5AqPXE7sE2", stats: { atk: 30, def: 20, sta: 20, accel: 30, endurance: 80 } },
            "Glide": { name: "G 滑行", type: "耐力型", weight: 2.5, shopeeUrl: "https://s.shopee.tw/9pbwYSb4Ew", stats: { atk: 20, def: 10, sta: 55, accel: 15, endurance: 30 } },
            "Hexa": { name: "H 六角軸心", type: "平衡型", weight: 2.6, shopeeUrl: "https://s.shopee.tw/9fIWM9bhZv", stats: { atk: 30, def: 35, sta: 20, accel: 15, endurance: 80 } },
            "High Needle": { name: "HN 高位針狀軸", type: "防禦型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/70HlBMJnRE", stats: { atk: 15, def: 55, sta: 20, accel: 10, endurance: 30 } },
            "High Taper": { name: "HT 高位錐形軸", type: "平衡型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/4AxZoFmzO7", stats: { atk: 30, def: 25, sta: 20, accel: 25, endurance: 80 } },
            "Ignition": { name: "I 點火", type: "攻擊型", weight: 2.4, shopeeUrl: "https://s.shopee.tw/8pjPMcesGm", stats: { atk: 50, def: 15, sta: 5, accel: 30, endurance: 80 } },
            "Kick": { name: "K 踢擊", type: "平衡型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/6ffDK8mIdB", stats: { atk: 35, def: 25, sta: 15, accel: 25, endurance: 80 } },
            "Level": { name: "L 水平", type: "攻擊型", weight: 2.7, shopeeUrl: "https://s.shopee.tw/7Kuu7UPLMW", stats: { atk: 40, def: 5, sta: 15, accel: 40, endurance: 80 } },
            "Low Flat": { name: "LF 低位偏平軸", type: "攻擊型", weight: 2.1, shopeeUrl: "https://s.shopee.tw/7AbBNfJA6H", stats: { atk: 45, def: 5, sta: 10, accel: 40, endurance: 80 } },
            "Low Orb": { name: "LO 矮球體", type: "耐力型", weight: 1.9, shopeeUrl: "https://s.shopee.tw/8V6rW309lB", stats: { atk: 5, def: 25, sta: 55, accel: 15, endurance: 30 } },
            "Low Rush": { name: "LR 低平軸心", type: "攻擊型", weight: 1.9, shopeeUrl: "https://s.shopee.tw/6Aiwk6sjC1", stats: { atk: 45, def: 5, sta: 15, accel: 35, endurance: 80 } },
            "Merge": { name: "M 融合", type: "平衡型", weight: 3.4, shopeeUrl: "https://s.shopee.tw/7Kuu8RHBVn", stats: { atk: 50, def: 20, sta: 10, accel: 20, endurance: 80 } },
            "Metal Needle": { name: "MN 金屬針狀軸", type: "防禦型", weight: 2.8, shopeeUrl: "https://s.shopee.tw/5L9XCZiIWX", stats: { atk: 8, def: 57, sta: 30, accel: 5, endurance: 30 } },
            "Needle": { name: "N 尖底軸心", type: "防禦型", weight: 2, shopeeUrl: "https://s.shopee.tw/7KubZyIWlG", stats: { atk: 10, def: 50, sta: 30, accel: 10, endurance: 30 } },
            "Orb": { name: "O 微球軸", type: "耐力型", weight: 2, shopeeUrl: "https://s.shopee.tw/6feumkL47C", stats: { atk: 10, def: 30, sta: 50, accel: 10, endurance: 30 } },
            "Point": { name: "P 針點平底軸心", type: "平衡型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/8fPzAJfVbl", stats: { atk: 25, def: 25, sta: 25, accel: 25, endurance: 80 } },
            "Quake": { name: "Q 躍動軸", type: "攻擊型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/9zvMlsPx9p", stats: { atk: 55, def: 15, sta: 5, accel: 25, endurance: 80 } },
            "Rubber Accel": { name: "RA 橡膠加速軸心", type: "攻擊型", weight: 3.1, shopeeUrl: "https://s.shopee.tw/5L9ssqCj0n", stats: { atk: 60, def: 17, sta: 3, accel: 20, endurance: 80 } },
            "Rush": { name: "R 奔馳軸", type: "攻擊型", weight: 2.1, shopeeUrl: "https://s.shopee.tw/40e9bwncj4", stats: { atk: 40, def: 10, sta: 20, accel: 30, endurance: 80 } },
            "Spike": { name: "S 尖刺軸", type: "防禦型", weight: 2, shopeeUrl: "https://s.shopee.tw/4VaQCrlii9", stats: { atk: 10, def: 45, sta: 35, accel: 10, endurance: 30 } },
            "Taper": { name: "T 錐形軸心", type: "平衡型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/7VE1mHHtQJ", stats: { atk: 35, def: 20, sta: 20, accel: 25, endurance: 80 } },
            "Trans Kick": { name: "TK 傳動踢擊", type: "平衡型", weight: 2.3, shopeeUrl: "https://s.shopee.tw/5VTJ5Mod88", stats: { atk: 35, def: 30, sta: 20, accel: 15, endurance: 80 } },
            "Trans Point": { name: "TP 變換", type: "平衡型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/8V6uf0NSxX", stats: { atk: 35, def: 25, sta: 25, accel: 15, endurance: 80 } },
            "Under Flat": { name: "UF 超平底軸", type: "攻擊型", weight: 2, shopeeUrl: "https://s.shopee.tw/9fIZbm3dI4", stats: { atk: 55, def: 5, sta: 5, accel: 35, endurance: 80 } },
            "Under Needle": { name: "UN 細尖防禦軸", type: "防禦型", weight: 1.9, shopeeUrl: "https://s.shopee.tw/9zviRwmVgY", stats: { atk: 10, def: 60, sta: 20, accel: 10, endurance: 30 } },
            "Unite": { name: "U 聯結軸", type: "平衡型", weight: 2.1, shopeeUrl: "https://s.shopee.tw/1qZf25P0jO", stats: { atk: 25, def: 25, sta: 30, accel: 20, endurance: 80 } },
            "Vortex": { name: "V 渦流", type: "攻擊型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/1gGEpmPe4N", stats: { atk: 45, def: 10, sta: 5, accel: 40, endurance: 80 } },
            "Wall Ball": { name: "WB 投牆球", type: "耐力型", weight: 2.2, shopeeUrl: "https://s.shopee.tw/BRmk7QLDi", stats: { atk: 15, def: 30, sta: 45, accel: 10, endurance: 30 } },
            "Wall Wedge": { name: "WW 防壁楔形", type: "防禦型", weight: 2.4, shopeeUrl: "https://s.shopee.tw/50X2V9AHpw", stats: { atk: 5, def: 60, sta: 25, accel: 10, endurance: 30 } },
            "Wedge": { name: "W 楔子", type: "防禦型", weight: 1.8, shopeeUrl: "https://s.shopee.tw/W4d8dEVFh", stats: { atk: 5, def: 55, sta: 30, accel: 10, endurance: 30 } },
            "Yielding": { name: "Y 降伏", type: "耐力型", weight: 4.2, shopeeUrl: "https://s.shopee.tw/9pcIG8NhKs", stats: { atk: 10, def: 15, sta: 65, accel: 10, endurance: 30 } },
            "Zap": { name: "Z 天蠍長矛", type: "平衡型", weight: 2.5, shopeeUrl: "https://s.shopee.tw/5AqShgK0xQ", stats: { atk: 30, def: 20, sta: 15, accel: 35, endurance: 80 } },
        }
    },
    sets: [
        { 
          name: "幻獸刺心 3-70D",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/2LWE4ATeqL",
          components: { blade: "Unicorn_Sting_v1", ratchet: "3-70", bit: "Dot" },
          versions: ["BX-35-03"]},
        { 
          name: "幻獸刺心 5-60GP",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/1gGXGt2TKQ",
          components: { blade: "Unicorn_Sting_v1", ratchet: "5-60", bit: "Gear Point" },
          versions: ["BX-26"]},
        { 
          name: "惡魔紅鐮 3-80B",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/6feuklV9ah",
          components: { blade: "Hells_Scythe_v1", ratchet: "3-80", bit: "Ball" },
          versions: ["BX-08-01"]},
        { 
          name: "惡魔紅鐮 3-85GB 金屬塗層:燦金",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/2qSCEEknmc",
          components: { blade: "Hells_Scythe_v2", ratchet: "3-85", bit: "Gear Ball" },
          versions: ["BX-48-04"]},
        { 
          name: "惡魔紅鐮 4-60T",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/3B52aGeJpd",
          components: { blade: "Hells_Scythe_v1", ratchet: "4-60", bit: "Taper" },
          versions: ["BX-02"]},
        { 
          name: "惡魔紅鐮 4-60T 金屬塗層:燦金",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/6VLUYVB7ZL",
          components: { blade: "Hells_Scythe_v2", ratchet: "4-60", bit: "Taper" },
          versions: ["BXG-03"]},
        { 
          name: "惡魔紅鐮 4-80LF",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/40e9cIxVJa",
          components: { blade: "Hells_Scythe_v1", ratchet: "4-80", bit: "Low Flat" },
          versions: ["BX-14-04"]},
        { 
          name: "惡魔鎖鏈 5-60HT",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/3Vhx5f1jbt",
          components: { blade: "Hells_Chain_v1", ratchet: "5-60", bit: "High Taper" },
          versions: ["BX-21-01"]},
        { 
          name: "惡魔鎖鏈 9-80O",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/6feyrV31ar",
          components: { blade: "Hells_Chain_v1", ratchet: "9-80", bit: "Orb" },
          versions: ["BX-31-03"]},
        { 
          name: "戰犀重角 3-80S",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/2LWCpCz16P",
          components: { blade: "Rhino_Horn_v1", ratchet: "3-80", bit: "Spike" },
          versions: ["BX-19"]},
        { 
          name: "戰犀重角 5-80Q",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/8pjgZBlhV6",
          components: { blade: "Rhino_Horn_v1", ratchet: "5-80", bit: "Quake" },
          versions: ["BX-31-06"]},
        { 
          name: "時鐘幻象 9-65B",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/2BCkkBDyro",
          components: { blade: "Clock_Mirage_v1", ratchet: "9-65", bit: "Ball" },
          versions: ["UX-16-01", "UX-16-02", "UX-16-03"]},
        { 
          name: "烈焰飛鳳S 3-80T",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/9pc2CDNckj",
          components: { blade: "DRANZER_SPIRAL_v1", ratchet: "3-80", bit: "Taper" },
          versions: ["BXG-01", "BXG-15"]},
        { 
          name: "王蛇鞭尾 3-80HN",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/5VTOYjle3M",
          components: { blade: "Viper_Tail_v1", ratchet: "3-80", bit: "High Needle" },
          versions: ["BX-16-03"]},
        { 
          name: "王蛇鞭尾 4-60F",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/7prJKyA8e8",
          components: { blade: "Viper_Tail_v1", ratchet: "4-60", bit: "Flat" },
          versions: ["BX-16-02"]},
        { 
          name: "王蛇鞭尾 5-60F",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/80AjXPeEUL",
          components: { blade: "Viper_Tail_v1", ratchet: "5-60", bit: "Flat" },
          versions: ["BX-24-04"]},
        { 
          name: "王蛇鞭尾 5-70D",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/9zvnv9Vcc9",
          components: { blade: "Viper_Tail_v1", ratchet: "5-70", bit: "Dot" },
          versions: ["BX-35-06"]},
        { 
          name: "王蛇鞭尾 5-80O",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/BRsCnDQxg",
          components: { blade: "Viper_Tail_v1", ratchet: "5-80", bit: "Orb" },
          versions: ["BX-16-01"]},
        { 
          name: "蒼穹龍神 4-60F",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/70HsYpmzVW",
          components: { blade: "Cobalt_Drake_v1", ratchet: "4-60", bit: "Flat" },
          versions: ["BXG-23"]},
        { 
          name: "蒼穹龍神 4-60F 金屬塗層",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/2qSJbCAle4",
          components: { blade: "Cobalt_Drake_v2", ratchet: "4-60", bit: "Flat" },
          versions: ["BXH-01"]},
        { 
          name: "蒼穹龍神 9-60R 金屬塗層",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/AKYKWze1yW",
          components: { blade: "Cobalt_Drake_v2", ratchet: "9-60", bit: "Rush" },
          versions: ["BX-46-01"]},
        { 
          name: "蒼龍利刃 2-80GP 金屬塗層",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/8KnCuLmina",
          components: { blade: "Dran_Dagger_v2", ratchet: "2-80", bit: "Gear Point" },
          versions: ["BXG-14"]},
        { 
          name: "蒼龍利刃 4-60R",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/7VE5umgFjW",
          components: { blade: "Dran_Dagger_v1", ratchet: "4-60", bit: "Rush" },
          versions: ["BX-20-01"]},
        { 
          name: "蒼龍利刃 4-70P",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/BRVBK7UVb",
          components: { blade: "Dran_Dagger_v1", ratchet: "4-70", bit: "Point" },
          versions: ["BX-31-04"]},
        { 
          name: "蒼龍利刃 7-55G",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/6L28Whijb8",
          components: { blade: "Dran_Dagger_v1", ratchet: "7-55", bit: "Glide" },
          versions: ["UX-18-05"]},
        { 
          name: "蒼龍利刃 9-60LF 金屬塗層",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/6feyvIoGM1",
          components: { blade: "Dran_Dagger_v2", ratchet: "9-60", bit: "Low Flat" },
          versions: ["BXG-25-03"]},
        { 
          name: "蒼龍神劍 3-60F",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/8ATiXKOiqK",
          components: { blade: "Dran_Sword_v1", ratchet: "3-60", bit: "Flat" },
          versions: ["BX-01", "BX-07", "BX-17-01", "BX-22"]},
        { 
          name: "蒼龍神劍 3-80B",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/2g8lzITkpq",
          components: { blade: "Dran_Sword_v1", ratchet: "3-80", bit: "Ball" },
          versions: ["BX-14-03"]},
        { 
          name: "蒼龍神劍 4-80DB 金屬塗層",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/180oQLUzv",
          components: { blade: "Dran_Sword_v2", ratchet: "4-80", bit: "Disc Ball" },
          versions: ["BXC-00-01", "BXC-00-02", "BXC-00-03", "BXG-12-04", "BXG-25-01", "BXG-52"]},
        { 
          name: "雄獅獵爪 0-80E",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/4fu2XszW6u",
          components: { blade: "Leon_Claw_v1", ratchet: "0-80", bit: "Elevate" },
          versions: ["UX-12-04"]},
        { 
          name: "雄獅獵爪 3-80HN",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/7fXe7I82dA",
          components: { blade: "Leon_Claw_v1", ratchet: "3-80", bit: "High Needle" },
          versions: ["BX-24-05"]},
        { 
          name: "雄獅獵爪 5-60P",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/9zvYtJNlJP",
          components: { blade: "Leon_Claw_v1", ratchet: "5-60", bit: "Point" },
          versions: ["BX-15"]},
        { 
          name: "雄獅獵爪 5-60P 金屬塗層",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/AUrpUYeB7g",
          components: { blade: "Leon_Claw_v2", ratchet: "5-60", bit: "Point" },
          versions: ["BXG-05"]},
        { 
          name: "飛龍旋翼 0-80C",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/2LW9vScntw",
          components: { blade: "Wyvern_Gale_v1", ratchet: "0-80", bit: "Cyclone" },
          versions: ["UX-12-06"]},
        { 
          name: "飛龍旋翼 2-60S",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/3Vi7JYejLx",
          components: { blade: "Wyvern_Gale_v1", ratchet: "2-60", bit: "Spike" },
          versions: ["UX-07-02"]},
        { 
          name: "飛龍旋翼 3-60T",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/7pr6TTHkJJ",
          components: { blade: "Wyvern_Gale_v1", ratchet: "3-60", bit: "Taper" },
          versions: ["BX-24-02"]},
        { 
          name: "飛龍旋翼 5-80GB",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/1BKCXABxSj",
          components: { blade: "Wyvern_Gale_v1", ratchet: "5-80", bit: "Gear Ball" },
          versions: ["BX-24-01"]},
        { 
          name: "騎士圓甲 3-85BS",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/8fQ3D77rX4",
          components: { blade: "Knight_Mail_v1", ratchet: "3-85", bit: "Bound Spike" },
          versions: ["UX-10-01"]},
        { 
          name: "騎士圓甲 3-85BS 金屬塗層",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/4LH43ANokD",
          components: { blade: "Knight_Mail_v2", ratchet: "3-85", bit: "Bound Spike" },
          versions: ["BXG-42"]},
        { 
          name: "騎士重盾 3-80N",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/AUrdKXMzf7",
          components: { blade: "Knight_Shield_v1", ratchet: "3-80", bit: "Needle" },
          versions: ["BX-04", "BX-06"]},
        { 
          name: "騎士重盾 3-80N 金屬塗層:燦金",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/5Aq6yxzQaf",
          components: { blade: "Knight_Shield_v2", ratchet: "3-80", bit: "Needle" },
          versions: ["BXH-02"]},
        { 
          name: "騎士重盾 4-60LF",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/9pbwXMTL1X",
          components: { blade: "Knight_Shield_v1", ratchet: "4-60", bit: "Low Flat" },
          versions: ["BX-14-05"]},
        { 
          name: "騎士重盾 4-80T",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/1BJyDPduaw",
          components: { blade: "Knight_Shield_v1", ratchet: "4-80", bit: "Taper" },
          versions: ["BX-08-02"]},
        { 
          name: "騎士重盾 5-80T",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/2LVvbbQ4tA",
          components: { blade: "Knight_Shield_v1", ratchet: "5-80", bit: "Taper" },
          versions: ["BX-20-03"]},
        { 
          name: "騎士長槍 3-60LF",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/qhGmDhN6x",
          components: { blade: "Knight_Lance_v1", ratchet: "3-60", bit: "Low Flat" },
          versions: ["BX-21-02"]},
        { 
          name: "騎士長槍 4-60GB",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/8KnHi1bNQp",
          components: { blade: "Knight_Lance_v1", ratchet: "4-60", bit: "Gear Ball" },
          versions: ["BX-24-03"]},
        { 
          name: "騎士長槍 4-80HN",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/1BK7AoOuLo",
          components: { blade: "Knight_Lance_v1", ratchet: "4-80", bit: "High Needle" },
          versions: ["BX-13"]},
        { 
          name: "魔導幻箭 3-60T",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/3B52axB3Xi",
          components: { blade: "Wizard_Arrow_v1", ratchet: "3-60", bit: "Taper" },
          versions: ["BX-14-06"]},
        { 
          name: "魔導幻箭 4-60N",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/gNhbvR9In",
          components: { blade: "Wizard_Arrow_v1", ratchet: "4-60", bit: "Needle" },
          versions: ["BX-08-03"]},
        { 
          name: "魔導幻箭 4-80B",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/110Y0Vc6FD",
          components: { blade: "Wizard_Arrow_v1", ratchet: "4-60", bit: "Ball" },
          versions: ["BX-03", "BX-05"]},
        { 
          name: "魔導幻箭 4-80B 水藍版",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/9fIWKvFT45",
          components: { blade: "Wizard_Arrow_v1", ratchet: "4-80", bit: "Ball" },
          versions: ["BX-17-02"]},
        { 
          name: "魔導幻箭 4-80GB",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/7KubYgspYH",
          components: { blade: "Wizard_Arrow_v1", ratchet: "4-80", bit: "Gear Ball" },
          versions: ["BX-24-06"]},
        { 
          name: "魔導幻箭 4-80N",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/8fPz96jXnC",
          components: { blade: "Wizard_Arrow_v1", ratchet: "4-80", bit: "Needle" },
          versions: ["BX-21-03"]},
        { 
          name: "魔導神杖 1-60R",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/8ATlhdoKSh",
          components: { blade: "Wizard_Rod_v1", ratchet: "1-60", bit: "Rush" },
          versions: ["BX-35-04"]},
        { 
          name: "魔導神杖 5-70DB",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/5fmQj1nnja",
          components: { blade: "Wizard_Rod_v1", ratchet: "5-70", bit: "Disc Ball" },
          versions: ["UX-03", "UX-04-02"]},
        { 
          name: "魔導神杖 5-70DB 金屬塗層",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/5fmQj44w4a",
          components: { blade: "Wizard_Rod_v2", ratchet: "5-70", bit: "Disc Ball" },
          versions: ["BXH-09"]},
        { 
          name: "魔獸護甲 1-80GF",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/1LdquC77nt",
          components: { blade: "Sphinx_Cowl_v1", ratchet: "1-80", bit: "Gear Flat" },
          versions: ["UX-07-03"]},
        { 
          name: "魔獸護甲 4-80HT",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/LlJieR2BS",
          components: { blade: "Sphinx_Cowl_v1", ratchet: "4-80", bit: "High Taper" },
          versions: ["BX-27-02"]},
        { 
          name: "魔獸護甲 5-60O",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/BRtWDuGdl",
          components: { blade: "Sphinx_Cowl_v1", ratchet: "5-60", bit: "Orb" },
          versions: ["BX-27-03"]},
        { 
          name: "魔獸護甲 9-80GN",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/4fuIt8DlZJ",
          components: { blade: "Sphinx_Cowl_v1", ratchet: "9-80", bit: "Gear Needle" },
          versions: ["BX-27-01"]},
        { 
          name: "鮫鯊狂鱗 4-50UF",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/1gGI5jIHaU",
          components: { blade: "Shark_Scale_v1", ratchet: "4-50", bit: "Under Flat" },
          versions: ["UX-15-01"]},
        { 
          name: "鮫鯊鋒鰭 1-60Q",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/AKYXOzbDzg",
          components: { blade: "Shark_Edge_v1", ratchet: "1-60", bit: "Quake" },
          versions: ["BX-31-05"]},
        { 
          name: "鮫鯊鋒鰭 2-60GP 金屬塗層",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/30lwfZg0cP",
          components: { blade: "Shark_Edge_v2", ratchet: "2-60", bit: "Gear Point" },
          versions: ["BXG-55"]},
        { 
          name: "鮫鯊鋒鰭 3-60LF",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/2Vpg4OBfiE",
          components: { blade: "Shark_Edge_v1", ratchet: "3-60", bit: "Low Flat" },
          versions: ["BX-14-01"]},
        { 
          name: "鮫鯊鋒鰭 3-80F",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/4LHKFs0HeD",
          components: { blade: "Shark_Edge_v1", ratchet: "3-80", bit: "Flat" },
          versions: ["BX-20-02"]},
        { 
          name: "鮫鯊鋒鰭 4-70E 金屬塗層",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/7Kuvpaasfw",
          components: { blade: "Shark_Edge_v2", ratchet: "4-70", bit: "Elevate" },
          versions: ["BX-48-02"]},
        { 
          name: "鮫鯊鋒鰭 4-80N",
          type: "防禦型",
          shopeeUrl: "https://s.shopee.tw/1gGZ4v9Akr",
          components: { blade: "Shark_Edge_v1", ratchet: "4-80", bit: "Needle" },
          versions: ["BX-14-02"]},
        { 
          name: "鮫鯊鋒鰭 5-60GF 金屬塗層",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/1BKIU5mJHH",
          components: { blade: "Shark_Edge_v2", ratchet: "5-60", bit: "Gear Flat" },
          versions: ["BXG-06"]},
        { 
          name: "鳳凰翔羽 2-60N",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/3LOqA5u76j",
          components: { blade: "Phoenix_Feather_v1", ratchet: "2-60", bit: "Needle" },
          versions: ["UX-12-05"]},
        { 
          name: "鳳凰飛翼 5-80H",
          type: "平衡型",
          shopeeUrl: "https://s.shopee.tw/2LVyuIOq5R",
          components: { blade: "Phoenix_Wing_v1", ratchet: "5-80", bit: "Hexa" },
          versions: ["BX-35-05"]},
        { 
          name: "鳳凰飛翼 9-60GF 金屬塗層",
          type: "攻擊型",
          shopeeUrl: "https://s.shopee.tw/8fQ2Rxvvwz",
          components: { blade: "Phoenix_Wing_v2", ratchet: "9-60", bit: "Gear Flat" },
          versions: ["BX-23", "BXG-35"]},
        { 
          name: "鳳凰飛翼 9-80DB",
          type: "耐力型",
          shopeeUrl: "https://s.shopee.tw/60PHH37nOM",
          components: { blade: "Phoenix_Wing_v2", ratchet: "9-80", bit: "Disc Ball" },
          versions: ["BXC-05"]},
    ]
};

/* ── 類型顏色 ── */
const TYPE_COLOR = {
  "攻擊型":"#D85A30","平衡型":"#D8A030","耐力型":"#1D9E75","防禦型":"#378ADD"
};
